# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Bots Build and Deploy

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with:
          name: jar
          path: build/libs/bots-1.0-SNAPSHOT.jar
  deploy:
    name: Deploy Fly
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download Jar
        uses: actions/download-artifact@v3
        with:
          name: jar
      - name: Fly Deploy
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set TWILIO_NUMBER=${{ secrets.TWILIO_NUMBER }}
      - run: flyctl secrets set TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}
      - run: flyctl secrets set TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}
      - run: flyctl secrets set CALENDAR_APP_NAME=${{ secrets.CALENDAR_APP_NAME }}
      - run: flyctl secrets set CALENDAR_TOKENS_DIR_PATH=${{ secrets.CALENDAR_TOKENS_DIR_PATH }}
      - run: flyctl secrets set CALENDAR_CREDENTIALS_FILE_PATH=${{ secrets.CALENDAR_CREDENTIALS_FILE_PATH }}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
